continuation_prompt = '[â¯â¯ ](fg:blue)'
right_format = """$gcloud"""

[directory]
style = "fg:blue"
format = "[$path]($style)"
truncation_length = 4
truncation_symbol = "..."
truncate_to_repo = false

[character]
success_symbol = '[â¯â¯â¯](fg:blue)'
error_symbol = '[â¯â¯â¯](fg:red)'


[git_status]
style = "fg:blue"
format = ' ([\[$all_status$ahead_behind\]]($style))'
conflicted = "âš”ï¸ "
untracked = "ğŸ†•" # ? ã‚’ ğŸ†• ã«å¤‰æ›´
modified = "ğŸ“"  # ! ã‚’ ğŸ“ ã«å¤‰æ›´
stashed = "ğŸ“¦"   # $ ã‚’ ğŸ“¦ ã«å¤‰æ›´


[git_branch]
format = " [$symbol $branch]($style)"
style = "fg:#888888"
symbol = "îœ¥"


[git_metrics]
disabled = false
added_style = 'bold blue'
format = ' \([+$added]($added_style)/[-$deleted]($deleted_style)\)'
only_nonzero_diffs = true

[package]
disabled = true

[cmd_duration]
show_milliseconds = true
format = ' [ó±«Œ $duration]($style)'

[gcloud]
symbol = 'ó±‡¶ '
style  = 'fg:#F7F7F7 bg:#7E8EF1'
format = '[î‚²](fg:#7E8EF1)[$symbol$project]($style)[â–“â–’](#7E8EF1)'

